version: '3'
services:
  web:
    image: ten7/flightdeck-web-7.4
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:cached
      - ./flight-deck.yml:/secrets/flight-deck-web.yml
    environment:
      EXP_USER: 'exp'
      EXP_PASS: 'exp'
      EXP_DB: 'exp'
      EXP_HOST: 'db'
      EXP_EMAIL_HOST: 'mailhog'
      EXP_EMAIL_PORT: 1025
      EXP_EMAIL_USER: ''
      EXP_EMAIL_PASS: ''
      EXP_EMAIL_PATH: ''
  db:
    image: ten7/flightdeck-db-10.4
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
      - ~/Sites/db-backups:/tmp/db-backups:cached
      - ./flight-deck.yml:/secrets/flight-deck-db.yml
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
